#+PROPERTY: header-args :results output

* Intro

#+title: Arrays

Yesterday we learned about the python interpreter and how it could handle numbers, text, and variables. We can add them together with the "+" symbol. We can set variables with the "=" sign. And lastly we learned we could combine the plus and the equals to modify a variable relative to its previous value.

* Lists

Python can handle lists. In fact, python can handle many kinds of lists. Today we will focus on what programmers call an "array". They can be created like this.

#+BEGIN_SRC python
  array_of_numbers = [ 0, 1, 99, 1000 ]
  print(array_of_numbers)
  animals = [ "pig", "cow", "chicken" ]
  print(animals)
#+END_SRC

* Definition of "Index"

Could someone tell me where they have heard the word "index" before?

* Indexing

In the back of your science textbooks you might have an index which gives you the page numbers of vocabulary words. This is simular to what we are referring to when we talk about an index of an array. But instead of the page number, the index refers to the ordered position of the vocab word in the book starting at 0. So the first vocab word has an index of 0, the second has 1, and the third has an index of 2.

* Indexing Example

In this example we are giving the index [1] to the list of items. We use the "[]" to make it clear to python we want to index the list.

#+BEGIN_SRC python
  my_array = [ "pig", "cow", "chicken" ]
  print(my_array[1])
#+END_SRC

* Empty List

Lists can be created with no items.

#+BEGIN_SRC python
  empty_array = []
  print(empty_array)
#+END_SRC

* Adding to List

Once created, either empty or with items, lists can be added to using the "append" command like this.

#+BEGIN_SRC python
  array = []
  array.append("cow")
  array.append("goat")
  print(array)
#+END_SRC

* Removing from list

We can use the "remove" command to remove an item from the list.

#+BEGIN_SRC python
  my_array = [ "pig", "cow", "chicken" ]
  my_array.remove("cow")
  print(my_array)
#+END_SRC

* Deleting by index

Remember we discussed that an index is a number refering to a position of an item on a list. We can use the "del" command (short for "delete") to remove an item only using the index

#+BEGIN_SRC python
  my_array = [ "pig", "cow", "chicken" ]
  del my_array[1]
  print(my_array)
#+END_SRC

* 2 Dimensional Arrays

Arrays can hold anything. This includes other arrays. So the following array has different animals seperated by species.

#+BEGIN_SRC python
animals = [ [ "Mocking", "Blue", "Cardinal" ],
            [ "Polar", "Grizzly", "Black" ],
            [ "Retriever", "Poodle", "Lab" ] ]
#+END_SRC

* Tic Tac Toe

To practice using 2 dimensianal arrays, we will play tic tac toe with a partner. It will not automatically determine a winner but will just keep track of the state of the board.

* Game Board

#+BEGIN_SRC python
  game_board = [ [ " ", " ", " " ], [ " ", " ", " " ], [ " ", " ", " " ] ]
  print(game_board[0])
  print(game_board[1])
  print(game_board[2])
#+END_SRC

#+RESULTS:
: [' ', 'X', ' ']
: [' ', ' ', 'O']
: [' ', ' ', ' ']
